import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {ConnectWallet} from "@thirdweb-dev/react";
import RewardCard from "@/components/Cards/RewardCard";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Stake & Rewards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="
        flex flex-col items-center justify-center py-2 min-h-screen
        bg-white dark:bg-gray-900
      ">
          <h1 className="text-4xl font-bold">Stake & Rewards</h1>
          <h2>
              Claim the NFTs below to stake them and earn rewards.
          </h2>
          <RewardCard nftRewardContractAddress={"0x33B86e9e1157D1D02204E797C31042cbc397c82d"} />
      </main>
    </>
  )
}
